[scripts]
test = "npx mocha --import=tsx tests/main.test.ts"
propose = "yarn run tsx scripts/initializeProposal.ts"
initialize-dao = "yarn run ts-node scripts/initializeDao.ts"
finalize = "yarn run ts-node scripts/finalizeProposal.ts"
metadata = "yarn run ts-node scripts/uploadMetadata.ts"
send-tokens = "yarn run ts-node scripts/sendTokens.ts"
crank = "yarn run ts-node scripts/crankTwap.ts"
attach-metadata = "yarn run ts-node scripts/attachMetadata.ts"
reclaim-tokens = "yarn run ts-node scripts/reclaimTokens.ts"
merge-tokens = "yarn run ts-node scripts/mergeTokens.ts"
setup-devnet = "yarn run tsx scripts/setupDevnet.ts"
resolve-outcome = "yarn run tsx scripts/resolveOutcome.ts"
add-v03-metadata = "yarn run tsx scripts/addV03Metadata.ts"

[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "AMMyu265tkBpRW21iGQxKGLaves3gKm2JcMUqfXNSpqD"
autocrat_migrator = "MigRDW6uxyNMDBD8fX2njCRyJC4YZk2Rx9pDUZiAESt"
autocrat = "autowMzCbM29YXMgVG3T62Hkgo7RcyrvgQQkd54fDQL"
conditional_vault = "VLTX1ishMBbcX3rdBWGssxawAo1Q2X2qxYFYqiGodVg"
optimistic_timelock = "tiME1hz9F5C5ZecbvE5z6Msjy8PKfTqo1UuRYXfndKF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"


[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb"
program = "./tests/fixtures/openbook_v2.so"

[[test.genesis]]
address = "TWAP7frdvD3ia7TWc8e9SxZMmrpd2Yf3ifSPAHS8VG3"
program = "./tests/fixtures/openbook_twap.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/fixtures/mpl_token_metadata.so"
